spring:
  datasource: # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/[DB_SCHEMA]?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: [DB_ID]
    password: [DB_PW]
  jpa:
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  file:
    name: ${user.dir}/log/testLog.log  # 로깅 파일 위치
  logback:
    rollingpolicy:
      max-history: 30 # 로그 파일 삭제 주기로, 30일 이후 로그는 삭제
      max-file-size: 10MB # 로그 파일 하나당 최대 파일 사이즈
  level:
    root: info